apiVersion: v1
kind: ConfigMap
metadata:
  name: uptime-monitor-config
  namespace: uptime-monitor
  labels:
    app: uptime-monitor
data:
  APP_NAME: "Uptime Monitor"
  DEBUG: "false"
  DEFAULT_CHECK_INTERVAL: "60"
