apiVersion: v1
kind: Service
metadata:
  name: uptime-monitor
  namespace: uptime-monitor
  labels:
    app: uptime-monitor
spec:
  type: ClusterIP
  selector:
    app: uptime-monitor
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
